version: '3.8'
name: "sovkombank-hackathon"

services:
  postgres:
    image: postgres
    container_name: postgres-sovkombank-hackathon
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./server/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - main

networks:
  main:

volumes:
  postgres_db_data: